[project]
name = "ml_19248"
version = "0.1.0"
description = "Machine Learning Coursework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.2",
    "scikit-learn>=1.7.2",
    "streamlit>=1.51.0",
]
